#!/usr/bin/env python3

import cog
import os
import sys
import re

from datetime import datetime
from jinja2 import FileSystemLoader, Environment

KEYWORDS = {
    "return": "ret",
    "break": "br",
    "continue": "cont",
    "nullptr": "null",
    "true": "t",
    "false": "f",
    "int": "i",
    "double": "d",
    "float": "f",
    "this": "thiz",
    "template": "tmpl",
    "if": "i",
    "else": "e",
    "while": "w",
    "for": "f",
}


def avoid_keyword(name):
    return KEYWORDS.get(name, name)


def make_env():
    templates = os.path.dirname(__file__)
    loader = FileSystemLoader(templates)
    env = Environment(
        loader=loader,
        cache_size=-1,
        lstrip_blocks=True,
        trim_blocks=True,
        line_statement_prefix="#",
        line_comment_prefix="##",
    )
    env.filters["as_comment"] = lambda comment: as_comment(comment, False)
    env.filters["as_doc"] = lambda comment: as_comment(comment, True)

    env.globals["make_warning"] = make_warning
    return env


def make_warning():
    program = sys.argv[0]
    date = datetime.now()
    warning = (
        f"Automatically generated by {program} at {date}.\n"
        f"Do not edit this file by hand. Do not include this file by itself."
    )
    return warning


def as_comment(comment, is_doc):
    if comment is None or comment == "":
        return ""
    lines = comment.split("\n")
    prefix = "///" if is_doc else "//"
    return "\n".join(f"{prefix} {line.rstrip()}" for line in lines) + "\n"


# Taken from https://stackoverflow.com/a/1176023
first_cap_re = re.compile("(.)([A-Z][a-z]+)")
all_cap_re = re.compile("([a-z0-9])([A-Z])")


def camel_to_snake(name):
    # s1 = first_cap_re.sub(r'\1_\2', name)
    return all_cap_re.sub(r"\1_\2", name).lower()


ENV = make_env()
