#!/usr/bin/env python3

from tools import run_clang_format, run_cog

cog_files = [
    "src/tiro/bytecode/instruction.cpp",
    "src/tiro/bytecode/instruction.hpp",
    "src/tiro/bytecode/disassembler.cpp",
    "src/tiro/bytecode/opcode.cpp",
    "src/tiro/bytecode/opcode.hpp",
    "src/tiro/bytecode/module.cpp",
    "src/tiro/bytecode/module.hpp",
    "src/tiro/bytecode_gen/gen_func.cpp",
    "src/tiro/bytecode_gen/gen_func.hpp",
    "src/tiro/bytecode_gen/locations.cpp",
    "src/tiro/bytecode_gen/locations.hpp",
    "src/tiro/ir/types.cpp",
    "src/tiro/ir/types.hpp",
    "src/tiro/ir_gen/support.cpp",
    "src/tiro/ir_gen/support.hpp",
]


def main():
    for file in cog_files:
        run_cog(file)
        run_clang_format(file)


if __name__ == "__main__":
    main()
