#!/usr/bin/env python3

from tools import run_clang_format, run_cog

cog_files = [
    "src/tiro/mir/new_types.hpp"
]


def main():
    for file in cog_files:
        run_cog(file)
        run_clang_format(file)


if __name__ == "__main__":
    main()
