#!/usr/bin/env python3

from tools import run_clang_format, run_cog
from argparse import ArgumentParser
from itertools import chain

FILES = {
    "ast": [
        "src/compiler/ast/decl.cpp",
        "src/compiler/ast/decl.hpp",
        "src/compiler/ast/dump.cpp",
        "src/compiler/ast/expr.cpp",
        "src/compiler/ast/expr.hpp",
        "src/compiler/ast/fwd.hpp",
        "src/compiler/ast/node.cpp",
        "src/compiler/ast/node.hpp",
        "src/compiler/ast/node_traits.hpp",
        "src/compiler/ast/stmt.cpp",
        "src/compiler/ast/stmt.hpp",
        "src/compiler/ast/visit.cpp",
        "src/compiler/ast/visit.hpp",
    ],
    "bytecode": [
        "src/compiler/bytecode/instruction.cpp",
        "src/compiler/bytecode/instruction.hpp",
        "src/compiler/bytecode/disassembler.cpp",
        "src/compiler/bytecode/op.cpp",
        "src/compiler/bytecode/op.hpp",
        "src/compiler/bytecode/module.cpp",
        "src/compiler/bytecode/module.hpp",
    ],
    "bytecode_gen": [
        "src/compiler/bytecode_gen/object.cpp",
        "src/compiler/bytecode_gen/object.hpp",
    ],
    "ir": [
        "src/compiler/ir/function.cpp",
        "src/compiler/ir/function.hpp",
        "src/compiler/ir/module.cpp",
        "src/compiler/ir/module.hpp",
    ],
    "ir_gen": [
        "src/compiler/ir_gen/compile_expr.cpp",
        "src/compiler/ir_gen/support.cpp",
        "src/compiler/ir_gen/support.hpp",
    ],
    "semantics": [
        "src/compiler/semantics/symbol_table.hpp",
        "src/compiler/semantics/symbol_table.cpp",
    ],
    "parser": ["src/compiler/parser/token.cpp", "src/compiler/parser/token.hpp",],
}


def main():
    parser = ArgumentParser()
    parser.add_argument(
        "modules",
        nargs="*",
        metavar="NAME",
        help="Use module names (see source) to only generate a few files. Leave empty to generate all.",
    )
    args = parser.parse_args()

    modules = args.modules
    files = None
    if modules:
        files = list(chain.from_iterable(FILES[module] for module in modules))
    else:
        files = list(chain.from_iterable(paths for module, paths in FILES.items()))

    run_cog(*files)
    run_clang_format(*files)


if __name__ == "__main__":
    main()
